a=input("enter number1")
b=input("enter number2")
print("addition of "+str(a)+" and "+str(b)+"="+str(a+b))
print("subtraction of "+str(a)+" and "+str(b)+"="+str(a-b))
print("multiplication of "+str(a)+" and "+str(b)+"="+str(a*b))
print("division of "+str(a)+" and "+str(b)+"="+str(float(a/b)))
print("modulus of "+str(a)+" and "+str(b)+"="+str(a%b))
print("power of "+str(a)+" and "+str(b)+"="+str(a**b))
